
## [References]{.text-background-brownDark .text-color-white .text-bold} (`[References]{.text-background-brownDark .text-color-white .text-bold}`)

The [`References`]{.text-background-brownDark .text-color-white .text-bold} table is a central component that serves all sections of the **[VegVault]{.text-background-black .text-color-white .text-bold}** database. This table contains all [`References`]{.text-background-brownDark .text-color-white .text-bold}, independent of the source of the [reference]{.text-background-brownDark .text-color-white .text-bold} and the type of data. Each row contains a single [`Reference`]{.text-background-brownDark .text-color-white .text-bold}, which is then linked to the type of data which is being referenced. This allows a single [`Reference`]{.text-background-brownDark .text-color-white .text-bold} to be used across data types, but also one data point having many different [references]{.text-background-brownDark .text-color-white .text-bold}.

Moreover, most [primary sources]{.text-background-brownDark .text-color-white .text-bold} of the data have a license, which requires [correct attribution]{.text-background-brownLight .text-color-black .text-bold}. Therefore, each [`Reference`]{.text-background-brownDark .text-color-white .text-bold} has information if such a [`Reference`]{.text-background-brownDark .text-color-white .text-bold} needs to be [cited]{.text-background-brownLight .text-color-black .text-bold} while using the specific data. 

