---
title: "Section I: Description of VegVault"
format:
  html:
    fig-width: 10
  gfm:
    fig-width: 10
editor: 
  markdown: 
    wrap: sentence
---
```{r}
#| label: source config
#| include: FALSE
#| results: 'hide'
#| warning: FALSE
#| message: FALSE

library(here)

here::i_am("Technical_overview/_01_section_I.qmd")

# Load configuration
source(
  here::here(
    "R/00_Config_file.R"
  )
)

source(
  here::here(
    "Technical_overview/00_Config_quarto.R"
  )
)

invisible(
  lapply(
    list.files(
      path = here::here("R/Functions"),
      pattern = "*.R",
      recursive = TRUE,
      full.names = TRUE
    ),
    source
  )
)
```

**VegVault** is a SQLite interdisciplinary database linking plot-based vegetation data with functional traits and climate.

Vault integrates data from multiple well-established sources to provide a comprehensive view of vegetation dynamics. By organizing data into clearly defined types and providing comprehensive referencing, VegVault supports detailed and high-quality ecological research. This structured approach ensures that data are accessible, reliable, traceable, and facilitate a wide range of analyses and applications across disciplines. See the Data Acquisition section for more details about reproducibility. 

## Data Structure
VegVault is organized into several section to systematically manage the varying datasets it integrates. The main structure is the `Dataset`, which serves as the cornerstone of the database structure. `Datasets` are further linked to `Samples`, representing individual data points within each dataset. Each `Dataset` can be linked to several `Samples` only if the samples differ in their age. Moreover, Each `Dataset` is classified into one of four types: 

- current vegetation plots,
- past vegetation (fossil pollen records) 
- functional traits
- gridpoint (a dataset type created to hold abiotic data, see details below).   

For current and past vegetation `Dataset`, the `Samples` holds information about their vegetation, and are linked to specific `Taxa`, which are the taxa names derived directly from the main data sources. `Trait` information is organised in separate `Datasets` (as they are associated with unique information about their spatio-temporal location, references, etc) but associated with these same `Taxa` codes as vegetation data. Moreover, each `Taxa` disregard of the source is associated with classification information (i.e. species, genus and family name).  "*Gridpoints*" are artificially created `Datasets` with even spatio-temporal resolution to hold the abiotic information. While the vegetation data is the main focus of the database, the structure of using separete `Datasets` ensuree a comprehensive organization of the data (see Figure XXX). Note that this is just a simplified description of the database structure, see XXX for full database structure.  
