// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table Datasets {
  dataset_id varchar [primary key]
}

Table DatasetSources {
  dataset_id varchar
  data_source varchar
}

Table DatasetType {
  dataset_id varchar
  dataset_type_id int
}

Table DatasetTypeID {
  dataset_type_id int [primary key]
  dataset_type varchar
}

Table DatasetCoord {
  dataset_id varchar
  long numeric 
  lat numeric
}

Table Samples {
  sample_id varchar [primary key]
}

Table DatasetSample {
  dataset_id varchar
  sample_id varchar
}

Table SampleAge {
  sample_id varchar
  age numeric
}

Table SampleUncern {
  sample_id varchar
  iteration int
  age int
}

Table SampleTaxa {
  sample_id varchar
  taxon_id varchar
  value numeric
}

Table SampleSize {
  sample_id varchar
  sample_size_id int 
}

Table SampleSizeID {
  sample_size_id int [primary key]
  sample_size numeric
}

Table SampleSizeDetails {
  sample_size_id int
  description varchar
}

Table Taxa {
  taxon_id int [primary key]
  taxon_name varchar
  }

Table TaxonClassification {
  taxon_id int
  taxon_name_raw int
  taxon_name_agree int
  taxon_name_exact bool [note: 'Does the name exactly match?']
  taxon_species int
  taxon_genus int
  taxon_family int
}

Ref: Datasets.dataset_id < DatasetCoord.dataset_id
Ref: Datasets.dataset_id < DatasetType.dataset_id
Ref: Datasets.dataset_id < DatasetSources.dataset_id
Ref: Datasets.dataset_id < DatasetSample.dataset_id

Ref: DatasetTypeID.dataset_type_id < DatasetType.dataset_type_id 

Ref: Samples.sample_id < DatasetSample.sample_id
Ref: Samples.sample_id < SampleAge.sample_id
Ref: Samples.sample_id < SampleTaxa.sample_id
Ref: Samples.sample_id < SampleSize.sample_id
Ref: Samples.sample_id < SampleUncern.sample_id

Ref: SampleSizeID.sample_size_id < SampleSizeDetails.sample_size_id 
Ref: SampleSizeID.sample_size_id < SampleSize.sample_size_id 

Ref: Taxa.taxon_id < SampleTaxa.taxon_id
Ref: Taxa.taxon_id < TaxonClassification.taxon_id
Ref: Taxa.taxon_id < TaxonClassification.taxon_name_raw
Ref: Taxa.taxon_id < TaxonClassification.taxon_name_agree
Ref: Taxa.taxon_id < TaxonClassification.taxon_species
Ref: Taxa.taxon_id < TaxonClassification.taxon_genus
Ref: Taxa.taxon_id < TaxonClassification.taxon_family




// Table users {
//   id integer [primary key]
//   username varchar
//   role varchar
//   created_at timestamp
// }

// Table posts {
//   id integer [primary key]
//   title varchar
//   body text [note: 'Content of the post']
//   user_id integer
//   status varchar
//   created_at timestamp
// }

// Ref: posts.user_id > users.id // many-to-one

